export const template1 = {
  type: 'tldr/clipboard',
  shapes: [
    {
      id: '56638425-a24d-469d-3ab7-f250e13265de',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1,
      point: [318.59, 357.53],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'black',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '3de47128-1f5e-4f2c-1f9a-9044f5b0adb8',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1.0625,
      point: [549.59, 357.53],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'black',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '022d852b-7244-4ea0-2432-f14c992115c5',
      type: 'text',
      name: 'Text',
      parentId: 'page',
      childIndex: 1.375,
      point: [318.59, 313.31],
      rotation: 0,
      text: 'Person Name',
      style: {
        color: 'black',
        size: 'small',
        isFilled: false,
        dash: 'draw',
        scale: 1.1672359455901713,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: 'bfb1f398-aa81-4a98-18cc-8cfec6128605',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1.125,
      point: [318.59, 653],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'black',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '88930fb9-4684-4010-1e97-5a9d72a5db3b',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1.4375,
      point: [549.59, 653],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'black',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '7c4608e4-6fef-4e76-3063-b212544e3e15',
      type: 'text',
      name: 'Text',
      parentId: 'page',
      childIndex: 1.625,
      point: [318.59, 608.78],
      rotation: 0,
      text: 'Person Name',
      style: {
        color: 'black',
        size: 'small',
        isFilled: false,
        dash: 'draw',
        scale: 1.1672359455901713,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: 'a35ccd0c-dd42-426c-0efb-f8ac09826371',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1.1875,
      point: [819.92, 357.53],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'yellow',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '7583b989-76e3-4452-2af8-7efe5ca2f54d',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1.25,
      point: [1050.92, 357.53],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'yellow',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '6e2d4def-882b-4c58-2079-19c161c831f7',
      type: 'text',
      name: 'Text',
      parentId: 'page',
      childIndex: 1.5,
      point: [819.92, 311.18],
      rotation: 0,
      text: 'Person Name',
      style: {
        color: 'black',
        size: 'small',
        isFilled: false,
        dash: 'draw',
        scale: 1.1672359455901713,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: 'e9a35078-e63e-4d95-131f-58f7fd1bdfe3',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1.3125,
      point: [824.19, 653],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'yellow',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '0754427d-3564-4419-33e5-b9b5a1bd1e8e',
      type: 'sticky',
      name: 'Sticky',
      parentId: 'page',
      childIndex: 1.5625,
      point: [1055.19, 653],
      size: [200, 200],
      text: '',
      rotation: 0,
      style: {
        color: 'yellow',
        size: 'large',
        isFilled: false,
        dash: 'draw',
        scale: 1,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '2bfacc78-0e1c-431c-0e8b-3a68b4ceeb44',
      type: 'text',
      name: 'Text',
      parentId: 'page',
      childIndex: 1.6875,
      point: [824.72, 609.85],
      rotation: 0,
      text: 'Person Name',
      style: {
        color: 'black',
        size: 'small',
        isFilled: false,
        dash: 'draw',
        scale: 1.1672359455901713,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: 'c5c61203-9a84-44ed-2ef1-31907849cea4',
      type: 'rectangle',
      name: 'Rectangle',
      parentId: 'page',
      childIndex: 1.75,
      point: [-267.41, 356.21],
      size: [453.26, 184.47],
      rotation: 0,
      style: {
        color: 'blue',
        size: 'small',
        isFilled: true,
        dash: 'solid',
        scale: 1,
      },
      label: '',
      labelPoint: [0.5, 0.5],
    },
    {
      id: '531a0458-73e9-4473-22a8-7f926598c136',
      type: 'text',
      name: 'Text',
      parentId: 'page',
      childIndex: 1.8125,
      point: [-270.61, 300.5],
      rotation: 0,
      text: 'Instructions',
      style: {
        color: 'black',
        size: 'small',
        isFilled: false,
        dash: 'draw',
        scale: 1.5744958393786423,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
    {
      id: '7c5d15ef-2625-4709-2fa5-ad32e009808c',
      type: 'triangle',
      name: 'Triangle',
      parentId: 'page',
      childIndex: 1.875,
      point: [-328.74, 305.3],
      size: [41.53, 38.46],
      rotation: 0,
      style: {
        color: 'yellow',
        size: 'small',
        isFilled: true,
        dash: 'draw',
        scale: 1,
      },
      label: '',
      labelPoint: [0.5, 0.5],
    },
    {
      id: 'c614bf0f-d593-4ed4-3252-977a4bbe2366',
      type: 'text',
      name: 'Text',
      parentId: 'page',
      childIndex: 1.9375,
      point: [-231.59, 381.17],
      rotation: 0,
      text: '1. Do something\n\n2. Do something twice\n\n3. Do something twice',
      style: {
        color: 'black',
        size: 'small',
        isFilled: false,
        dash: 'draw',
        scale: 1.33404767890135,
        font: 'Graphik Web',
        textAlign: 'start',
        textWeight: 'normal',
        listType: 'none',
        textDecoration: 'none',
        fontStyle: 'normal',
      },
    },
  ],
  bindings: [],
  assets: [],
  zoom: 0.75,
}
